"""Renamed books.author column

Revision ID: 75232a2bc3c5
Revises: c7a6b43bf028
Create Date: 2023-07-28 19:14:27.598616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75232a2bc3c5"
down_revision = "c7a6b43bf028"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "author", new_column_name="author_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "author_name", new_column_name="author")
    # ### end Alembic commands ###
