"""Added Author table and relation

Revision ID: a7a355b92ac2
Revises: 8a98e5a11d0b
Create Date: 2023-07-28 19:47:20.595351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a355b92ac2'
down_revision = '8a98e5a11d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
