"""Added table 'genres'

Revision ID: c7a6b43bf028
Revises: 4350b8f49338
Create Date: 2023-07-28 16:10:02.818555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a6b43bf028'
down_revision = '4350b8f49338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
